#!/bin/sh


module=aesdchar

modprobe ${module} || exit 1

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
rm -f /dev/${module}
mknod /dev/${module} c $major 0
chgrp sudo /dev/${module}
chmod 664 /dev/${module}