#!/bin/sh


module=aesdchar

MODULE_PATH="/lib/modules/$(uname -r)/extra/"

insmod ${MODULE_PATH}/${module}.ko || exit 1

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
rm -f /dev/${module}
mknod /dev/${module} c $major 0
chgrp wheel /dev/${module}
chmod 664 /dev/${module}