#!/bin/sh

# script gets installed to /etc/init.d
# scull and module load/unload scripts will also be installed here

# Get the directory of the script and define paths
DIR=$(dirname "$(readlink -f "$0")")
MODULE_PATH="/lib/modules/$(uname -r)/extra/"

case "$1" in
    start)
        cd ${MODULE_PATH} && ${DIR}/scull_load && ${DIR}/module_load faulty
        modprobe hello
        ;;
    stop)
        rmmod hello
        ${DIR}/module_unload faulty
        ${DIR}/scull_unload
        ;;
    restart)
        echo "Restarting..."
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
exit 0